name: Build Browser Extensions

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Build (webpack)
        run: npm run build

      - name: Prepare Chrome extension
        run: |
          mkdir -p extension-chrome
          cp -r dist/* extension-chrome/
          cp manifest.json extension-chrome/manifest.json

      - name: Prepare Firefox extension
        run: |
          mkdir -p extension-firefox
          cp -r dist/* extension-firefox/
          cp manifest.firefox.json extension-firefox/manifest.json

      - name: Zip Chrome extension
        run: cd extension-chrome && zip -r ../extension-chrome.zip .

      - name: Zip Firefox extension
        run: cd extension-firefox && zip -r ../extension-firefox.zip .

      - name: Upload Chrome extension artifact
        uses: actions/upload-artifact@v4
        with:
          name: extension-chrome
          path: extension-chrome.zip

      - name: Upload Firefox extension artifact
        uses: actions/upload-artifact@v4
        with:
          name: extension-firefox
          path: extension-firefox.zip